# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

AS_SRC += pltcall32.S
AS_SRC += pltctrl32.S
AS_SRC += upltinit32.S
SRC += elfexec.c

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
