# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

include $(TOP)/../../Makefile.conf

AS_SRC64 += pltcall32.S
AS_SRC64 += pltctrl32.S
AS_SRC64 += upltinit32.S
SRC64 += elfexec.c

include $(srcdir)/$(TOP)/../makefile.inc
