# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

AS_SRC += my_cs.S
AS_SRC += my_ds.S
AS_SRC += my_ss.S

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
