# Copyright (C) 1999 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1996 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += modfl.c
SRC += modf.c
SRC += huge_val.c

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
