# Copyright (C) 2014 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2013 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../../..

SRC += genvsec.c

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
