# Copyright (C) 1994 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += closedir.c
SRC += odflags.c
SRC += opendir.c
SRC += readdir.c
SRC += rewinddi.c
SRC += seekdir.c
SRC += telldir.c

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
