# Copyright (C) 2014 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2013 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../../..

SRC += c_initnt.c
AS_SRC += s_initnt.S
SRC += c_socket.c
AS_SRC += s_socket.S
SRC += c_close.c
AS_SRC += s_close.S
SRC += c_connct.c
AS_SRC += s_connct.S
SRC += c_send.c
AS_SRC += s_sendto.S
AS_SRC += s_send.S
SRC += c_errors.c
SRC += c_select.c
AS_SRC += s_select.S
SRC += c_recv.c
AS_SRC += s_recvfr.S
AS_SRC += s_recv.S
SRC += c_listen.c
AS_SRC += s_listen.S
SRC += c_bind.c
AS_SRC += s_bind.S
SRC += c_accept.c
AS_SRC += s_accept.S
SRC += c_gprnm.c
AS_SRC += s_gprnm.S
SRC += c_gscknm.c
AS_SRC += s_gscknm.S
SRC += c_ioctl.c
SRC += c_fcntl.c
SRC += c_nblkio.c
AS_SRC += s_gnblk.S
AS_SRC += s_snblk.S
SRC += c_shtdwn.c
SRC += c_sckopt.c
SRC += c_sockpr.c
AS_SRC += vxd.S

include $(TOP)/../makefile.inc
