# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += ctime.c
SRC += difftime.c
SRC += strftime.c
SRC += time.c

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
