# Copyright (C) 2014 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2013 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../../..

SRC += i_ntoa.o
SRC += i_addr.o
SRC += i_lnaof.o
SRC += i_mkaddr.o
SRC += i_net.o
SRC += i_netof.o
SRC += gprtbynm.o
SRC += gprtbyn2.o
SRC += gprtent.o
SRC += gnetbynm.o
SRC += gnetent.o
SRC += gnetbyad.o
SRC += gsrvbynm.o
SRC += gsrvent.o
SRC += shstent.o
SRC += l_res.o
SRC += r_data.o
SRC += l_herrno.o
SRC += ghstnmad.o
SRC += gsrvbypt.o
SRC += i_nsap.o
SRC += herror.o
SRC += r_debug.o
SRC += r_mkqry.o
SRC += r_qry.o
SRC += r_init.o
SRC += r_comp.o
SRC += r_send.o
SRC += bresvpt.o
SRC += rcmd.o
SRC += rexec.o
SRC += rusrpass.o
SRC += i_pton.o
SRC += i_ntop.o

include $(TOP)/../makefile.inc
