# Copyright (C) 2014 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2013 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../../..

SRC += i_ntoa.c
SRC += i_addr.c
SRC += i_lnaof.c
SRC += i_mkaddr.c
SRC += i_net.c
SRC += i_netof.c
SRC += gprtbynm.c
SRC += gprtbyn2.c
SRC += gprtent.c
SRC += gnetbynm.c
SRC += gnetent.c
SRC += gnetbyad.c
SRC += gsrvbynm.c
SRC += gsrvent.c
SRC += shstent.c
SRC += l_res.c
SRC += r_data.c
SRC += l_herrno.c
SRC += ghstnmad.c
SRC += gsrvbypt.c
SRC += i_nsap.c
SRC += herror.c
SRC += r_debug.c
SRC += r_mkqry.c
SRC += r_qry.c
SRC += r_init.c
SRC += r_comp.c
SRC += r_send.c
SRC += bresvpt.c
SRC += rcmd.c
SRC += rexec.c
SRC += rusrpass.c
SRC += i_pton.c
SRC += i_ntop.c
SRC += gaddrinf.c

include $(TOP)/../makefile.inc
