# Copyright (C) 2014 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2013 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += initnt.c
SRC += fsext.c
SRC += socket.c
SRC += sockpr.c
SRC += bind.c
SRC += listen.c
SRC += accept.c
SRC += recv.c
SRC += send.c
SRC += connct.c
SRC += gscknm.c
SRC += gprnm.c
SRC += close.c
SRC += sckopt.c
SRC += shtdwn.c
SRC += ioctl.c
SRC += select.c
SRC += fcntl.c
#SRC += newerror.c
SRC += dnsaddr.c
SRC += ini.c
SRC += hstnm.c
SRC += config.c
SRC += addr.c
SRC += if.c
SRC += sockmark.c
#SRC += uname.c
SRC += windows.c

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
