# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=..

SRC += bioscom.c
SRC += biosdisk.c
SRC += biosequi.c
SRC += bioskey.c
SRC += biosmem.c
SRC += biosprin.c
SRC += biostime.c
SRC += b_time.c

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
