# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details

LIB = $(TOP)/../../lib

all ::
	../makemake.exe
	$(MAKE) -f makefile.sub
	../makemake.exe -2
	$(MAKE) -C dj64 final

include $(srcdir)/$(TOP)/../makefile.inc

clean ::
	$(TOP)/../makemake.exe
	$(MAKE) -f makefile.sub SUBARGS=clean
	@-$(RM) makefile.oi makefile.rf makefile.rfo
