# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# -*- makefile -*-

CROSS_PREFIX ?= i686-linux-gnu-
CROSS_GCC = $(CC)
CROSS_CPP = $(CPP)
# for AS objects
CROSS_AS := $(CROSS_PREFIX)as
CROSS_ASAR = $(CROSS_PREFIX)ar
CROSS_ASLD = $(CROSS_PREFIX)ld
CROSS_ASCPP = $(CPP) -x assembler-with-cpp $(1) | $(CROSS_AS) --32 -
CROSS_ASSTRIP = $(CROSS_PREFIX)strip

# for mkproto.sh
export CROSS_ASLD
