# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# -*- makefile -*-

CROSS_PREFIX ?= i686-linux-gnu-
# for AS objects
CROSS_AS := $(CROSS_PREFIX)as
CROSS_AR = $(CROSS_PREFIX)ar
CROSS_LD = $(CROSS_PREFIX)ld
CROSS_STRIP = $(CROSS_PREFIX)strip
