# Copyright (C) 2013 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2003 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2002 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += errhandl.c
SRC += hugevalf.c
SRC += hugevall.c
SRC += rint.c
SRC += rintf.c
SRC += rintl.c
SRC += lrintf.c
SRC += lrint.c
SRC += lrintl.c
SRC += llrintf.c
SRC += llrint.c
SRC += llrintl.c
SRC += nan_def.c
SRC += nan.c
SRC += nanf.c
SRC += nanl.c
SRC += fpclassf.c
SRC += fpclassd.c
SRC += sgnbitd.c
SRC += sgnbitf.c
SRC += sgnbitld.c

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
