# Copyright (C) 1998 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += doserr2e.c
SRC += doserrno.c

include $(TOP)/../../Makefile.conf
include $(srcdir)/$(TOP)/../makefile.inc
