name: Build and test
on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
      - synchronize
  push:

jobs:
  Build_and_test:
    name: Build and test

    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Package install
      run: ./ci_prereq.sh

    - name: Build
      id: build
      run: |
        make deb
        sudo dpkg -i ../dj32*.deb
        sudo dpkg -i ../dj64*.deb
        sudo dpkg -i ../libdjdev64*.deb
        sudo dpkg -i ../libdjstub64*.deb
        sudo dpkg -i ../djdev64*.deb

    - name: Upload failure logs
      if: ${{ always() && (steps.build.outcome == 'failure') }}
      uses: actions/upload-artifact@v6
      with:
        name: failure-logs
        path: build/contrib/ncurses/build32/config.log

    - name: Set up test environment
      run: |
        ./ci_test_prereq.sh

    - name: Run tests
      run: |
        ./ci_test.sh
